version: "3.8"
services:
  webapp:
    container_name: webapp
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo-db:27017
    depends_on:
      - mongo-db
  mongo-db:
    container_name: mongo-db
    image: mongo
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
